import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
import joblib
import os

print("Loading massive dataset from CSV...")
# Load the dataset from the CSV file generated by generate_data.py
df = pd.read_csv('corporate_tickets.csv')

print(f"Dataset loaded with {len(df)} records.")

# converting text to matrix
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(df['text'])
y = df['category']

# Training the Logistic Regression model on the big dataset
print("Training Logistic Regression model on scalable data...")
model = LogisticRegression()
model.fit(X, y)

# Save the model for use in the API
os.makedirs('model_assets', exist_ok=True)
joblib.dump(model, 'model_assets/classifier.joblib')
joblib.dump(vectorizer, 'model_assets/vectorizer.joblib')

print("(Success) The upgraded AI model is trained and saved.")